CREATE USER admin WITH LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION; GRANT postgres TO admin;



CREATE DATABASE limb WITH OWNER = postgres ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;